apiVersion: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    uid: pyroscope
    isDefault: true
    editable: false
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: ffzytyvhrfmrkf
    isDefault: false
    editable: false
