spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cosmos
    username: cosmos
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800
  refresh-token-expiration: 1209600

cookie:
  secure: false

ai:
  root-url : ${AI_BASE_URL}