spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXP:1800}
  refresh-token-expiration: ${REFRESH_TOKEN_EXP:1209600}

cookie:
  secure: true

ai:
  root-url: ${AI_SERVER_BASE_URL:http://ai-server:8000}
  server:
    base-url: ${AI_SERVER_BASE_URL:http://ai-server:8000}
    connect-timeout: ${AI_SERVER_CONNECT_TIMEOUT:3s}
    read-timeout: ${AI_SERVER_READ_TIMEOUT:30s}

judge0:
  base-url: ${JUDGE0_BASE_URL:https://dev-judge.cosmoscode.site}

server:
  servlet:
    context-path: /api